### ISSUE TITLE
Service no longer running?

### ISSUE THREAD

**Issue by erunion** [alexgodin/corgibomb#2]
http://corgibomb.heroku.com/ is 404'ing currently.

**Comment by alexgodin** [comment]
OH NOOOOOOO.

I WILL INVESTIGATE.

**Comment by yahelc** [comment]
HI @alexgodin, it looks like it's still down. Do you plan on resurrecting?

**Comment by franc0is** [comment]
Still 404'ing. Any plans to bring it back?

**Comment by erunion** [comment]
¯\_(ツ)_/¯
